"""nullable_material_id

Revision ID: 475eb726bd5f
Revises: 7824b7c20ed9
Create Date: 2026-03-19 00:14:59.482776

"""
from alembic import op
import sqlalchemy as sa


revision = '475eb726bd5f'
down_revision = '7824b7c20ed9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('flashcards', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('quizzes', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quizzes', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('flashcards', 'material_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###