"""add_avatar_config

Revision ID: a209bc6a686c
Revises: 475eb726bd5f
Create Date: 2026-04-21 22:27:24.587415

"""
from alembic import op
import sqlalchemy as sa


revision = 'a209bc6a686c'
down_revision = '475eb726bd5f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_config', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_config')
    # ### end Alembic commands ###